{% set name = "pyWinhook" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 9ff70e8df522c2703e54af551c6a69b93def20dbe47ff2137a7fbb9d44720a49

build:
  number: 0
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - swig
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyWinhook

about:
  home: https://github.com/Tungsteno74/pyWinhook
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A fork of pyHook from Peter P. with some updates'
  description: |
    A pyHook fork with some updates for support latest Visual Studio
    compilers.

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
