travis:
  secure:
    BINSTAR_TOKEN: DQwf1Kgd/p3DpFGEj6slz4o7d/P7/gZ4e1iaQMbg9UbU3s/2bid/jWK258igcf5m6lN4eZ5IQSWNUD8d8Hn5wgJWQvPClEAWzSi/8cjr7M8URGzrQZY3rkaInGA5G7MEJbdkZLtWblrWuykEIHDvqcEGcyUy0dPjCSZqpfFPdj8Rgg01sOHEBumBTN9bbCZFJgwnA7QpM9+vU+8YKfE3vcQCNsEgzQMskE4xmE5JubD7W7ur8yXdVQP/8DYjow3TTkfItDp42x3LIhw6N4FfQTJ4qrXWoccctMM4vkCqJ0/eo5Dd+Bq9krQoVA9xEigAnvTDEIhp5H6WQEwWKliDtnBRJn2tVgYdrTndVNjUYrbBse77uhDV5ngiLGOtxgZRLFw5E0RkGQmZRzK1/EJz3omX7kxRdchmQVdSPj98kco5gJdW47FDintYiE24uK4f7EmA7kNak+3OZ7CmLhIkjgjeoqdE2K4FestCfUSvg+e1avwHbvIBrGrw5ELFbpPbAfYyV/06TO7YSLooi0DCr8nJfo6CW48Sfx5/Uvx2mtcAUZ6MNUZjVdbA6R7DrmjGfLXYIvuY1psGrYRG8nxXLnrjAAssvAUcGX6sBSDcaF5WDsNOXp2t1ijAjb0x37C2wHkwO2FzEPUMmqFDFQa+IcfVnXt32mF6So/F+YfpHbY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
