appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bikthnoPldLRtUHkPTf2mEfyC7nhV9yrLeA3BXAcIBrfs9YoiGpXODFNWtW2UKksaMUroT0vD73QvQsp40jZHmjoGRKjHn69YerkGuDgYB293aLkAwxhHF4Io2UaVfxYPg81yPpiI2T6UIMpXdpsty3XVhOH452/hSUeGFm83vt+/cDpv1/4qF/h6dPW1nEb2YVvzfWQ0Adie2BbhTqV2Q+e+3SdmojcimgLGCLrWHUAKjwRKtbzXK5H50NoP5nUhUGZ1jVBAHcekw6sgFtFRpah4oGajyHHEw4oeRPu9wE375WgaggNC4RiuLalJM1U5oSvWTRzvUNNVO5psoS87Ew35ZVDqjWAfBtoNiJs8O3gPDH61rSUA911tTFoRJpwgxAL0MMSp5G3JPPXdnEDjLQDi+vhD67Ov2t4aJNWqITK65n0J1e0+MZLLnC1p3Zu+tc8hhxIxDUIRcwfjQ1q/yHTloVcQXuAbPnu1qgnBB8zuz69Se5SUuNxS4YV9S8V8sZi+u+az2XogDoLwsz/UMZYlgIryY9jakclYfM+aQ+ak80L6BvQs8+2a2vVxAGdgvWW9A77DmeDNfkO4yXrXpemeAXjgHH0LNw1rDxHT+lzMkC3BwimBuItLR2eqTYO2PR740EuoyA7w3dJ/3rwjsau5Dn8stY/ZkJqmYBes3U=}
provider:
  win: azure
